apiVersion: v1

kind: Pod

metadata:

  name: flaskpod

spec:

  containers:

  - name: flask

    image: wab109/flaskapp:latest

    ports:

            - containerPort: 5000
  imagePullSecrets:
  - name: docker-pull-secret
