apiVersion: v1
kind: Service
metadata:
  name: flasksvc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "RG12"
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: flaskapp



'''
apiVersion: v1
kind: Service
metadata:
  name: flasksvc
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: flaskapp
'''